In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LinearRegression

In [2]:
from sklearn.datasets import load_digits
digits=load_digits()

In [3]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [4]:
x=digits.data
y=digits.target

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.2)

In [6]:
lr=LinearRegression()
lr.fit(x_train,y_train)
lr.score(x_train,y_train)

0.5952414640966524

In [7]:
svm=SVC()
svm.fit(x_train,y_train)
svm.score(x_train,y_train)

0.9979123173277662

In [8]:
rf=RandomForestClassifier()
rf.fit(x_train,y_train)
rf.score(x_train,y_train)

1.0

In [9]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)

In [10]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [11]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [12]:
get_score(lr,x_train,x_test,y_train,y_test)

0.5894340022928864

In [13]:
get_score(rf,x_train,x_test,y_train,y_test)

0.9638888888888889

In [14]:
get_score(svm,x_train,x_test,y_train,y_test)

0.9777777777777777

In [15]:
from sklearn.model_selection import cross_val_score


In [16]:
a=cross_val_score(lr,x,y,cv=3)
a

array([0.52105031, 0.56814242, 0.41943985])

In [17]:
b=cross_val_score(rf,x,y,cv=3)
b

array([0.93489149, 0.95158598, 0.92654424])

In [18]:
c=cross_val_score(svm,x,y,cv=3)
c

array([0.96494157, 0.97996661, 0.96494157])

In [19]:
import numpy as np
np.average(a)

0.5028775279011323

In [20]:
np.average(b)

0.9376739009460211

In [21]:
np.average(c)

0.9699499165275459

In [22]:
from sklearn.datasets import load_iris
iris=load_iris()

In [23]:
dir(iris)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [24]:
df=pd.DataFrame(iris['data'],columns=iris['feature_names'])
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [25]:
df['target']=iris['target']
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [26]:
x=df.drop('target',axis=1)
x

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [27]:
y=df['target']
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int32

In [38]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()

In [39]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()

In [40]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [41]:
from sklearn.svm import SVC
svm=SVC()

In [42]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [43]:
from sklearn.model_selection import cross_val_score

In [47]:
l_scores = cross_val_score(lr,x, y,cv=5)
l_scores

array([0.        , 0.85124923, 0.        , 0.76155439, 0.        ])

In [49]:
d_scores = cross_val_score(dt, x, y,cv=5)
d_scores

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])