In [1]:
import numpy as np
a=np.array([5,5,4])
print(a)

[5 5 4]


In [2]:
x=a.dtype
print(x)

int32


In [3]:
x=a.ndim
print(x)

1


In [4]:
b=np.array([[4,3],[5,6],[6,4]])
print(b)

[[4 3]
 [5 6]
 [6 4]]


In [7]:
b.dtype

dtype('int32')

In [8]:
b.ndim

2

In [9]:
a.itemsize

4

In [10]:
b.itemsize

4

In [12]:
b=np.array([[4,3],[5,6],[6,4]],dtype=np.float64)
print(b)


[[4. 3.]
 [5. 6.]
 [6. 4.]]


In [13]:
b.itemsize

8

In [14]:
a.size

3

In [15]:
b.size

6

In [16]:
b.shape

(3, 2)

In [18]:
b=np.array([[4,3],[5,6],[6,4]],dtype=complex)
print(b)

[[4.+0.j 3.+0.j]
 [5.+0.j 6.+0.j]
 [6.+0.j 4.+0.j]]


In [24]:
import numpy as np
c=np.zeros((3,4))
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [27]:
d=np.ones((3,4))
print(d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [28]:
b[1]

array([5.+0.j, 6.+0.j])

In [29]:
l=range(5)
print(l)

range(0, 5)


In [30]:
l[0]

0

In [31]:
l[4]

4

In [32]:
q=np.arange(1,7)
print(q)

[1 2 3 4 5 6]


In [33]:
q=np.arange(1,7,2)
print(q)

[1 3 5]


In [37]:
q=np.linspace(0,10,5)
print(q)

[ 0.   2.5  5.   7.5 10. ]


In [38]:
b

array([[4.+0.j, 3.+0.j],
       [5.+0.j, 6.+0.j],
       [6.+0.j, 4.+0.j]])

In [42]:
b=np.array([[4,3],[5,6],[6,4]],dtype=int)
print(b)

[[4 3]
 [5 6]
 [6 4]]


In [43]:
b.reshape(2,3)

array([[4, 3, 5],
       [6, 6, 4]])

In [47]:
b.ravel()

array([4, 3, 5, 6, 6, 4])

In [48]:
b

array([[4, 3],
       [5, 6],
       [6, 4]])

In [49]:
b.sum(axis=0)

array([15, 13])

In [50]:
b.sum(axis=1)

array([ 7, 11, 10])

In [52]:
np.sqrt(b)

array([[2.        , 1.73205081],
       [2.23606798, 2.44948974],
       [2.44948974, 2.        ]])

In [53]:
np.mean(b)

4.666666666666667

In [54]:
np.std(b)

1.1055415967851332

In [55]:
np.var(b)

1.222222222222222

In [56]:
b

array([[4, 3],
       [5, 6],
       [6, 4]])

In [57]:
b*b

array([[16,  9],
       [25, 36],
       [36, 16]])

In [58]:
b+b

array([[ 8,  6],
       [10, 12],
       [12,  8]])

In [59]:
b**b

array([[  256,    27],
       [ 3125, 46656],
       [46656,   256]], dtype=int32)

In [3]:
import numpy as np
s=np.ones((3,4))
s

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
s.ndim

2

In [9]:
arr=np.array([[1,2],[3,4]])
arr.ndim

2

In [12]:
arr=np.array([[1,2],[3,4]],ndmin=5)
arr

array([[[[[1, 2],
          [3, 4]]]]])

In [13]:
arr.ndim

5